### ISSUE TITLE
Translate xkcd comics to greek

### ISSUE THREAD

**Issue by evgepab** [dmst-sweng/swebok-el#54]
At first I found the original xkcd font but sadly, even though someone had mentioned it, they hadn't added the Greek alphabet yet. However, the comic sans font was the one I thought was closer to that, so I tried to make a translation of the comic [here](https://github.com/dmst-sweng/swebok-el/blob/82626ac27b8ab02ef772de55015c74f23efe5950/xkcd/Software%20Requirements/use%20case.png) and that's the result:

![Screenshot from 2023-04-16 21-10-27](https://user-images.githubusercontent.com/79972107/232333292-dc59ef3a-c5a1-4cd4-bcf5-b2e7ba199908.png)

It's not direct translation since I tried to adjust it to the Greek reality.

Kindly let me now how you feel about the font, the translation and if you would like me to continue with other translations.

**Comment by dspinellis** [comment]
Nice!  Go for it!  If you're doing the translations in an open-source vector drawing program (e.g. Inkscape), then please also put the corresponding files also under version control.
